name: scribbaloo
favicon: null
layout_spectrum: 0.24113
typography_spectrum: 0.06438
title: simple ideas to inspire creativity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5ec049'
    - '#f8ee59'
    - '#fb733b'
    - '#9458a0'
    - '#1a3709'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.3418890491593629
purpose: []
